Traceback (most recent call last):
  File "./frankenstein.py", line 16, in <module>
    import scripts.iqfeed.dbhist as dbhist
  File "E:\Frankenstein\scripts\iqfeed\dbhist.py", line 28, in <module>
    import beCOMPANY.settings as settings
  File "E:\Frankenstein\beCOMPANY\settings.py", line 128, in <module>
    django.setup()
  File "d:\anaconda2\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "d:\anaconda2\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "d:\anaconda2\lib\site-packages\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "d:\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "d:\anaconda2\lib\site-packages\django\contrib\auth\models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "d:\anaconda2\lib\site-packages\django\contrib\auth\base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "d:\anaconda2\lib\site-packages\django\db\models\base.py", line 108, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "d:\anaconda2\lib\site-packages\django\db\models\base.py", line 307, in add_to_class
    value.contribute_to_class(cls, name)
  File "d:\anaconda2\lib\site-packages\django\db\models\options.py", line 263, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "d:\anaconda2\lib\site-packages\django\db\__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "d:\anaconda2\lib\site-packages\django\db\utils.py", line 212, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "d:\anaconda2\lib\site-packages\django\db\utils.py", line 116, in load_backend
    return import_module('%s.base' % backend_name)
  File "d:\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "d:\anaconda2\lib\site-packages\django\db\backends\postgresql\base.py", line 24, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: DLL load failed: The paging file is too small for this operation to complete.
