Traceback (most recent call last):
  File "./frankenstein.py", line 6, in <module>
    import pandas as pd
  File "d:\anaconda2\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "d:\anaconda2\lib\site-packages\pandas\compat\__init__.py", line 357, in <module>
    from dateutil import parser as _date_parser
  File "d:\anaconda2\lib\site-packages\dateutil\parser.py", line 1171, in <module>
    class _tzparser(object):
  File "d:\anaconda2\lib\site-packages\dateutil\parser.py", line 1173, in _tzparser
    class _result(_resultbase):
  File "d:\anaconda2\lib\site-packages\dateutil\parser.py", line 1178, in _result
    class _attr(_resultbase):
MemoryError
