Traceback (most recent call last):
  File "./frankenstein.py", line 3, in <module>
    
  File "d:\anaconda2\lib\site-packages\requests\__init__.py", line 52, in <module>
    try:
  File "d:\anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "d:\anaconda2\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "d:\anaconda2\lib\site-packages\OpenSSL\crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "d:\anaconda2\lib\site-packages\cryptography\hazmat\primitives\asymmetric\rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "d:\anaconda2\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 7, in <module>
    import pkg_resources
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2985, in <module>
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2971, in _call_aside
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 3018, in _initialize_master_working_set
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 700, in add_entry
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 1990, in find_on_path
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2399, in from_location
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2740, in _reload_version
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2364, in _version_from_file
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2532, in _get_metadata
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 1472, in get_metadata_lines
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 1468, in get_metadata
    
  File "d:\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 1578, in _get
    
IOError: [Errno 12] Not enough space
