no mem for new parser
Traceback (most recent call last):
  File "./frankenstein.py", line 5, in <module>
    import numpy as np
  File "d:\anaconda2\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "d:\anaconda2\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "d:\anaconda2\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "d:\anaconda2\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "d:\anaconda2\lib\site-packages\numpy\core\__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "d:\anaconda2\lib\site-packages\numpy\testing\__init__.py", line 10, in <module>
    from unittest import TestCase
  File "d:\anaconda2\lib\unittest\__init__.py", line 59, in <module>
    from .case import (TestCase, FunctionTestCase, SkipTest, skip, skipIf,
  File "d:\anaconda2\lib\unittest\case.py", line 6, in <module>
    import difflib
  File "d:\anaconda2\lib\difflib.py", line 37, in <module>
    Match = _namedtuple('Match', 'a b size')
  File "d:\anaconda2\lib\collections.py", line 386, in namedtuple
    exec class_definition in namespace
MemoryError
